/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_emoge_app_emoge_ui_CameraActivity */

#ifndef _Included_com_emoge_app_emoge_ui_CameraActivity
#define _Included_com_emoge_app_emoge_ui_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_emoge_app_emoge_ui_CameraActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_emoge_app_emoge_ui_CameraActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
